SELECT * FROM movies
FETCH FIRST ROW ONLY

SELECT * FROM movies
ORDER BY 3 DESC	
FETCH FIRST 5 ROW ONLY

SELECT * FROM directors
ORDER BY 4 
FETCH FIRST 5 ROW ONLY

SELECT * FROM actors
WHERE gender = 'F'
ORDER BY 5 DESC
FETCH FIRST 10 ROW ONLY

SELECT * FROM movies
ORDER BY 3 DESC
FETCH FIRST 5 ROW ONLY OFFSET 5

--OFFSET can uses before FETCH
SELECT * FROM movies
ORDER BY 3 DESC
OFFSET 5
FETCH FIRST 5 ROW ONLY 
